Ignore errors while checking discovery status
Apparently just querying the status of a node being discovered can
trigger a NodeLocked error from Ironic, so we need to handle
failures or set -e will kill us.

Change-Id: I275d189c5cfa7216de321ad6edc10a6bdec5ff05

diff --git a/scripts/instack-ironic-deployment b/scripts/instack-ironic-deployment
--- a/scripts/instack-ironic-deployment
+++ b/scripts/instack-ironic-deployment
@@ -146,7 +146,10 @@ function discover_nodes {
     for node_id in $node_ids; do
         echo -n "       Result for node $node_id is ... "
         while true; do
-            finished=$(openstack baremetal introspection status $node_id -f value -c finished)
+            # NOTE(bnemec): Even though we're just reading the status, this can fail with
+            # a NodeLocked error from Ironic.  In that case we just want to keep retrying,
+            # so ignore the failure or set -e will stop us.
+            finished=$(openstack baremetal introspection status $node_id -f value -c finished || echo "Error")
             if [ "$finished" = "True" ]; then
                 error=$(openstack baremetal introspection status $node_id -f value -c error)
                 if [ "$error" = "None" ]; then
@@ -156,6 +159,8 @@ function discover_nodes {
                 fi
                 ironic node-set-provision-state $node_id provide
                 break
+            elif [ "$finished" = "Error" ]; then
+                echo "Ignoring previous error."
             fi
             sleep 15
         done
