Remove plan creation and adding roles to it from instack-deploy-overcloud
Plan is created and Roles added to it during undercloud installation
https://github.com/rdo-management/tripleo-image-elements/blob/mgt-master
/elements/tuskar/os-refresh-config/post-configure.d/101-plan-add-roles#L15-L28

Change-Id: Idfd943f4bb6253437b4385f5ac3aa29bd5c12ff7

diff --git a/scripts/instack-deploy-overcloud b/scripts/instack-deploy-overcloud
--- a/scripts/instack-deploy-overcloud
+++ b/scripts/instack-deploy-overcloud
@@ -160,24 +160,11 @@ function create_cephx_key() {
 if [ -n "$TUSKAR" ]; then
 
     PLAN_ID=$(tuskar plan-show overcloud | awk '$2=="uuid" {print $4}')
-    if [ -n "$PLAN_ID" ]; then
-        tuskar plan-delete $PLAN_ID
+
+    if [ -z "$PLAN_ID" ]; then
+        echo "Could not find overcloud plan" 1>&2
+        exit 1
     fi
-
-    tuskar plan-create overcloud
-    PLAN_ID=$(tuskar plan-show overcloud | awk '$2=="uuid" {print $4}')
-
-    CONTROLLER_ID=$(tuskar role-list | awk '$4=="Controller" {print $2}')
-    COMPUTE_ID=$(tuskar role-list | awk '$4=="Compute" {print $2}')
-    SWIFT_ID=$(tuskar role-list | awk '$4=="Swift-Storage" {print $2}')
-    CINDER_ID=$(tuskar role-list | awk '$4=="Cinder-Storage" {print $2}')
-    CEPH_ID=$(tuskar role-list | awk '$4=="Ceph-Storage" {print $2}')
-
-    tuskar plan-add-role $PLAN_ID -r $CONTROLLER_ID
-    tuskar plan-add-role $PLAN_ID -r $COMPUTE_ID
-    tuskar plan-add-role $PLAN_ID -r $SWIFT_ID
-    tuskar plan-add-role $PLAN_ID -r $CINDER_ID
-    tuskar plan-add-role $PLAN_ID -r $CEPH_ID
 
     export TUSKAR_PARAMETERS=${TUSKAR_PARAMETERS:-"
     -A NeutronControlPlaneID=${NeutronControlPlaneID}
